# Generated by Django 5.2.2 on 2025-06-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapp', '0002_room_rename_end_time_booking_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
